report/urls.py
from django.conf.urls import include, url
from report import views

urlpatterns = [
    url(r'^reports/$', views.view_all_reports, name='report_all'),

    url(
        r'^report/(?P<report_id>[-\w\d]+)/$',
        views.view_report,
        name='view_report'
    ),

    url(
        r'^report/xml/(?P<report_id>[-\w\d]+)/$',
        views.view_xml_report,
        name='view_xml_report'
    ),

    url(
        r'^report/pdf/(?P<report_id>[-\w\d]+)/$',
        views.view_pdf_report,
        name='view_pdf_report'
    ),
]

suadetest/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView



urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name="index.html"), name='index'),

    url(r'^', include('report.urls', namespace="report")),

    url(r'^admin/', admin.site.urls),
]

report/models.py
from __future__ import unicode_literals
from django.contrib.postgres.fields import JSONField

from django.db import models

# Create your models here.

class Report(models.Model):
    type = models.TextField()

    class Meta:
        managed = False
        db_table = 'reports'

report/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Report
import json
import dicttoxml

from django.views.generic.detail import SingleObjectMixin
from easy_pdf.views import PDFTemplateView

def view_all_reports(request):
    template_name = 'report/view_all_reports.html'
    reports = Report.objects.all()
    context = {
        'reports': reports
    }
    return render(request, template_name, context)


def view_report(request, report_id):
    template_name = 'report/view_report.html'
    report = get_object_or_404(Report, id=report_id)
    context = {
        'report': report
    }
    return render(request, template_name, context)

def view_xml_report(request, report_id):
    report = get_object_or_404(Report, id=report_id)
    data = json.loads(report.type)
    xml = dicttoxml.dicttoxml(data)
    return HttpResponse(xml, content_type='text/xml')

def view_pdf_report(request, report_id):
    report = get_object_or_404(Report, id=report_id)
    data = json.loads(report.type)
    xml = dicttoxml.dicttoxml(data)
    return HttpResponse(xml, content_type='text/xml')

class ReportPdfView(SingleObjectMixin, PDFTemplateView):

    template_name = "report/report_pdf_template.html"
    queryset = Report.objects.all()

    def get_object(self):
        report = get_object_or_404(Report, id=self.kwargs.get('report_id', None))
        return report

    def get_context_data(self, **kwargs):
        self.object = self.get_object()
        context = super(ReportPdfView, self).get_context_data(**kwargs)
        context['pagesize'] = "A4"
        report = json.loads(self.object.type)
        context['report'] = report
        return context

view_pdf_report = ReportPdfView.as_view()

report/templates/report/report_pdf_template.html
<style>
    .title {
        text-align: center;
        font-weight: bold;
        font-size: 350%;
    }

    .text-center {
        text-align: center;
    }

    .text-left {
        text-align: left;
    }

    .text-right {
        text-align: right;
    }

</style>

{% block content %}

    <div class="title">
        The Report
    </div>

    <div class="text-right">
        <strong>Organization: </strong> {{ report.organization }}
        <br>
        <strong>Reported: </strong>: </strong> {{ report.reported_at }}
        <br>
        <strong>Created: </strong> {{ report.created_at }}
        <br>
    </div>

    <div class="text-center">
        For item in inventory:
        <br>
        {{ report.inventory|length }} item(s)
        <br>
        {% for i in report.inventory %}
            <strong>{{ i.name }}</strong>: {{ i.price }}
            <br>
        {% endfor %}
    </div>

{% endblock %}

report/templates/report/view_all_reports.html
{% extends "index.html" %}

{% block title %}
    Suade Reports
{% endblock %}


{% block content %}
    <div class="container">
        <div class="starter-template">
            <h1>All Reports</h1>

            <table class="table">
                {% for r in reports %}
                    <tr>
                        <th>
                            <a href="{% url 'report:view_report' report_id=r.id %}">{{ r.id }}</a>
                        </th>

                        <th><a href="{% url 'report:view_pdf_report' report_id=r.id %}">PDF Report</a>
                        </th>

                        <th><a href="{% url 'report:view_xml_report' report_id=r.id %}">XML Report</a>
                        </th>
                    </tr>
                {% endfor %}
            </table>
        </div>

    </div>
{% endblock %}

report/templates/report/view_report.html
{% extends "index.html" %}

{% block title %}
    Suade Reports {{ report.id }}
{% endblock %}


{% block content %}
    <div class="container">
        <div class="starter-template">
            <h1>This is report {{ report.id }}</h1>
        </div>

        <P>
            <a href="{% url 'report:view_pdf_report' report_id=report.id %}">PDF Report</a>
            <br>
            <a href="{% url 'report:view_xml_report' report_id=report.id %}">XML Report</a>
        </P>
    </div>
{% endblock %}

templates/index.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>{% block title %}
        Suade Test
    {% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="{% static 'css/starter-template.css' %}">


</head>

<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Suade Test</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a href="/">Home</a></li>
                <li><a href="{% url 'report:report_all' %}">Reports</a></li>
            </ul>
        </div>
        <!--/.nav-collapse -->
    </div>
</nav>

{% block content %}
    <div class="container">

        <div class="starter-template">
            <h1>The Task</h1>

            <p class="lead">You need to implement the Report Exporting Service. The purpose of this service is to take abstract
                reports and generate PDF documents and XML files out of them.
                Services within the Suade system are stand-alone (flask) python applications with a thin layer of
                (RESTful) web services as the interface.</p>
        </div>

    </div>
{% endblock %}





<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>


</body>
</html>